#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# CPE v2.2 format only
# Based on CPE file: https://nvd.nist.gov/feeds/json/cpematch/1.0/nvdcpematch-1.0.json.zip
#
# Dictionary built with script "cpe.py"

cpe_match = {
    'Apache/Jserv': 'cpe:/a:apache:jserv',
    'Apache/Tomcat': 'cpe:/a:apache:tomcat',
    'Microsoft/ftpd': 'cpe:/a:ftpd:ftpd',
    'GNU/Inetutils': 'cpe:/a:gnu:inetutils',
    'Proftpd': 'cpe:/a:proftpd:proftpd',
    'Pureftpd': 'cpe:/a:pureftpd:pureftpd',
    'Serv-u': 'cpe:/a:serv-u:serv-u',
    'Vsftpd': 'cpe:/a:beasts:vsftpd',
    'Adobe/Coldfusion': 'cpe:/a:adobe:coldfusion',
    'Apache/Axis2': 'cpe:/a:apache:axis2',
    'Apache/Tomcat': 'cpe:/a:apache:tomcat',
    'Eclipse/Jetty': 'cpe:/a:eclipse:jetty',
    'Jboss': 'cpe:/a:jboss:jboss',
    'Redhat/JBoss Web Server': 'cpe:/a:redhat:jboss_web_server',
    'Jenkins': 'cpe:/a:jenkins:jenkins',
    'Oracle/Glassfish': 'cpe:/a:oracle:glassfish',
    'Oracle/Weblogic Server': 'cpe:/a:oracle:weblogic_server',
    'Oracle/Application Server': 'cpe:/a:oracle:application_server',
    'Phusion/Passenger': 'cpe:/a:phusion:passenger',
    'Railo': None,
    'Caucho Technology/Resin': 'cpe:/a:caucho_technology:resin',
    'Websphere Application Server': 'cpe:/a:ibm:websphere_application_server',
    'Zope': 'cpe:/a:zope:zope',
    'Google/App Engine': 'cpe:/a:google:app_engine_python_sdk',
    'SAP/Netweaver': 'cpe:/a:sap:netweaver',
    'Winstone/Servlet Container': None,
    'Apachefriends/XAMPP': 'cpe:/a:apache_friends:xampp',
    'Imatix/Xitami': 'cpe:/a:imatix:xitami',
    'aeSecure/aeSecure': None,
    'Phion/Ergon/Airlock': None,
    'Alert Logic/Alert Logic': None,
    'Alibaba Cloud Computing/AliYunDun': None,
    'Anquanbao/Anquanbao': None,
    'AnYu Technologies/AnYu': None,
    'Approach/Approach': None,
    'Armor/Armor Defense': None,
    'Microsoft/ASP.NET Generic Protection': None,
    'Czar Securities/Astra Web Protection': None,
    'Amazon/AWS Elastic Load Balancer': None,
    'Baidu Cloud Computing/Yunjiasu': None,
    'Ethic Ninja/Barikode': None,
    'Barracuda Networks/Barracuda Application Firewall': None,
    'Faydata Technologies Inc./Bekchy': None,
    'BinarySec/BinarySec': None,
    'BitNinja/BitNinja': None,
    'BlockDoS/BlockDoS': None,
    'Bluedon IST/Bluedon': None,
    'Varnish/CacheWall': None,
    'CdnNs/WdidcNet/CdnNS Application Gateway': None,
    'Cerber Tech/WP Cerber Security': None,
    'ChinaCache/ChinaCache CDN Load Balancer': None,
    'Yunaq/Chuang Yu Shield': None,
    'Cisco/ACE XML Gateway': 'cpe:/h:cisco:ace_xml_gateway',
    'Penta Security/Cloudbric': None,
    'Cloudflare Inc./Cloudflare': None,
    'Amazon/Cloudfront': None,
    'Comodo CyberSecurity/Comodo cWatch': None,
    'Jean-Denis Brun/CrawlProtect': None,
    'Rohde & Schwarz CyberSecurity/DenyALL': None,
    'Distil Networks/Distil': None,
    'DOSarrest Internet Security/DOSarrest': None,
    'Applicure Technologies/DotDefender': None,
    'DynamicWeb/DynamicWeb Injection Check': None,
    'Verizon Digital Media/Edgecast': None,
    'EllisLab/Expression Engine': 'cpe:/a:ellislab:expressionengine',
    'F5 Networks/BIG-IP Access Policy Manager': 'cpe:/a:f5:big-ip_access_policy_manager',
    'F5 Networks/BIG-IP Application Security Manager': 'cpe:/a:f5:big-ip_application_security_manager',
    'F5 Networks/BIG-IP Local Traffic Manager': 'cpe:/a:f5:big-ip_local_traffic_manager',
    'F5 Networks/FirePass': 'cpe:/h:f5:firepass',
    'F5 Networks/Trafficshield': None,
    'Fortinet/FortiWeb': 'cpe:/a:fortinet:fortiweb',
    'GoDaddy/GoDaddy Website Protection': None,
    'Grey Wizard/Greywizard': None,
    'Art of Defense/HyperGuard': 'cpe:/a:artofdefence:hyperguard',
    'IBM/DataPower': 'cpe:/a:ibm:datapower_gateway',
    'CloudLinux/Imunify360': None,
    'Imperva Inc./Incapsula': None,
    'Instart Logic/Instart DX': None,
    'Microsoft/ISA Server': 'cpe:/a:microsoft:isa_server',
    'Janusec/Janusec Application Gateway': None,
    'Jiasule/Jiasule': None,
    'KnownSec/KS-WAF': None,
    'Akamai/Kona Site Defender': None,
    'LiteSpeed Technologies/LiteSpeed Firewall': None,
    'Inactiv/Malcare': None,
    'Mission Control/Mission Control Application Shield': None,
    'SpiderLabs/ModSecurity': 'cpe:/a:mod_security:mod_security',
    'NBS Systems/NAXSI': 'cpe:/a:naxsi_project:naxsi',
    'PentestIt/Nemesida': None,
    'Barracuda Networks/NetContinuum': None,
    'Citrix Systems/NetScaler AppFirewall': None,
    'AdNovum/NevisProxy': None,
    'NewDefend/Newdefend': None,
    'NexusGuard/NexusGuard Firewall': None,
    'NinTechNet/NinjaFirewall': None,
    'NSFocus Global Inc./NSFocus': None,
    'BlackBaud/OnMessage Shield': None,
    'Palo Alto Networks/Palo Alto Next Gen Firewall': None,
    'PerimeterX/PerimeterX': None,
    'PowerCDN/PowerCDN': None,
    'ArmorLogic/Profense': 'cpe:/a:armorlogic:profense_web_application_firewall',
    'Radware/AppWall': 'cpe:/h:radware:appwall',
    'Reblaze/Reblaze': None,
    'RSJoomla!/RSFirewall': None,
    'Microsoft/ASP.NET RequestValidationMode': None,
    'Sabre/Sabre Firewall': None,
    'Safe3/Safe3 Web Firewall': None,
    'SafeDog/Safedog': None,
    'Chaitin Tech./Safeline': None,
    'SecuPress/SecuPress WordPress Security': None,
    'United Security Providers/Secure Entry': None,
    'BeyondTrust/eEye SecureIIS': None,
    'Imperva Inc./SecureSphere': 'cpe:/a:imperva:securesphere',
    'Neusoft/SEnginx': None,
    'One Dollar Plugin/Shield Security': None,
    'SiteGround/SiteGround': None,
    'Sakura Inc./SiteGuard': None,
    'TrueShield/Sitelock': None,
    'Dell/SonicWall': 'cpe:/h:dell:sonicwall_network_security_appliance_250m',
    'Sophos/UTM Web Protection': None,
    'Squarespace/Squarespace': None,
    'StackPath/StackPath': None,
    'Sucuri Inc./Sucuri CloudProxy': None,
    'Tencent Technologies/Tencent Cloud Firewall': None,
    'Citrix Systems/Teros': None,
    'TransIP/TransIP Web Firewall': None,
    'iFinity/DotNetNuke/URLMaster SecurityCheck': None,
    'Microsoft/URLScan': 'cpe:/a:microsoft:urlscan',
    'OWASP/Varnish': 'cpe:/a:varnish-cache:varnish',
    'VirusDie LLC/VirusDie': None,
    'Wallarm Inc./Wallarm': None,
    'WatchGuard Technologies/WatchGuard': None,
    'WebARX Security Solutions/WebARX': 'cpe:/a:webarxsecurity:webarx',
    'AQTRONIX/WebKnight': None,
    'IBM/WebSEAL': 'cpe:/a:ibm:webseal',
    'WebTotem/WebTotem': None,
    'Feedjit/Wordfence': 'cpe:/a:wordfence:wordfence',
    'WTS/WTS-WAF': None,
    '360 Technologies/360WangZhanBao': None,
    'XLabs/XLabs Security WAF': None,
    'Yundun/Yundun': None,
    'Yunsuo/Yunsuo': None,
    'Zenedge/Zenedge': None,
    'Accenture/ZScaler': None,
    'West263 Content Delivery Network': None,
    'pkSecurity Intrusion Detection System': None,
    'Xuanwudun': None,
    'Open-Resty Lua Nginx WAF': None,
    '3dcart': None,
    'Advanced Electron Forum': 'cpe:/a:anelectron:advanced_electron_forum',
    'Afosto': None,
    'Afterbuy': None,
    'Ametys Cms': 'cpe:/a:ametys:ametys',
    'Apostrophe Cms': None,
    'Arastta': None,
    'Aspnetforum': None,
    'Beehive Forum': 'cpe:/a:beehive_forum:beehive_forum',
    'Bigcommerce': None,
    'Bigware Shop': 'cpe:/a:bigware:bigware_shop',
    'Bizweb': None,
    'Bolt': 'cpe:/a:bolt:bolt',
    'Browsercms': 'cpe:/a:brave:browser',
    'Bubble': None,
    'Burning Board': 'cpe:/a:woltlab:burning_board',
    'Adobe/Business Catalyst': None,
    'Ckan': None,
    'Clientexec': 'cpe:/a:clientexec:clientexec',
    'Cloudcart': None,
    'Colormeshop': None,
    'Contao Cms': 'cpe:/a:contao:contao',
    'Contendio': 'cpe:/a:contenido:contendio',
    'Contensis Cms': None,
    'Contentbox': None,
    'Contentful': None,
    'Cpg Dragonfly Cms': 'cpe:/a:cpg-nuke:cpg_dragonfly_cms',
    'Cotonti Siena': 'cpe:/a:cotonti:cotonti_siena',
    'Craft Cms': 'cpe:/a:craftcms:craft_cms',
    'Danneo/Cms': 'cpe:/a:danneo:cms',
    'Sitecore/Cms': 'cpe:/a:sitecore:cms',
    'Cms Made Simple': 'cpe:/a:cms_made_simple:cms_made_simple',
    'Cmsimple': 'cpe:/a:cmsimple:cmsimple',
    'Concrete5': 'cpe:/a:concrete5:concrete5',
    'Dedecms': 'cpe:/a:dedecms:dedecms',
    'Discourse': 'cpe:/a:discourse:discourse',
    'Discuz': 'cpe:/a:comsenz:discuz',
    'Django Cms': 'cpe:/a:django-cms:django_cms',
    'Dokuwiki': 'cpe:/a:dokuwiki:dokuwiki',
    'Dotcms': 'cpe:/a:dotcms:dotcms',
    'Dotnetnuke': 'cpe:/a:dotnetnuke:dotnetnuke',
    'Lotus/Domino': 'cpe:/a:lotus:domino',
    'Drupal': 'cpe:/a:drupal:drupal',
    'E107': 'cpe:/a:e107:e107',
    'Episerver': 'cpe:/a:episerver:episerver',
    'Expressionengine': 'cpe:/a:expressionengine:expressionengine',
    'Ez Publish': 'cpe:/a:ez:ez_publish',
    'Flarum': 'cpe:/a:flarum:flarum',
    'Flexcmp': None,
    'Fluxbb': 'cpe:/a:fluxbb:fluxbb',
    'Fork Cms': 'cpe:/a:fork-cms:fork_cms',
    'Fudforum': 'cpe:/a:fudforum:fudforum',
    'Getsimple Cms': 'cpe:/a:cagintranetworks:getsimple_cms',
    'Ghost Cms': 'cpe:/a:ghost:ghost',
    'Gravcms': 'cpe:/a:getgrav:grav_cms',
    'Hippo Cms': None,
    'Hotaru Cms': 'cpe:/a:hotaru:hotaru_cms',
    'Impresspages Cms': 'cpe:/a:impresspages:impresspages_cms',
    'Indexhibit': 'cpe:/a:indexhibit:indexhibit',
    'Invision Power Board': 'cpe:/a:invision_power_services:invision_power_board',
    'Jalios Jcms': None,
    'Jimdo': None,
    'Jforum': 'cpe:/a:jforum:jforum',
    'Joomla': 'cpe:/a:joomla:joomla',
    'Koken': None,
    'Kooboo Cms': None,
    'Lepton-cms/Lepton': 'cpe:/a:lepton-cms:lepton',
    'Liferay': 'cpe:/a:liferay:liferay',
    'Livejournal': 'cpe:/a:livejournal:livejournal',
    'Livestreet': 'cpe:/a:livestreet:livestreet',
    'Magento': 'cpe:/a:magento:magento',
    'Majordomo': 'cpe:/a:great_circle_associates:majordomo',
    'Mambo': 'cpe:/a:mambo:mambo',
    'Squiz/Matrix': 'cpe:/a:squiz:matrix',
    'Mediawiki': 'cpe:/a:mediawiki:mediawiki',
    'Minibb': 'cpe:/a:minibb:minibb',
    'Mercuryboard': 'cpe:/a:mercuryboard:mercuryboard',
    'Modx Revolution': 'cpe:/a:modx:modx_revolution',
    'Moodle': 'cpe:/a:moodle:moodle',
    'Moto Cms': None,
    'Movable Type': 'cpe:/a:six_apart:movable_type',
    'Mura Cms': 'cpe:/a:blueriver:mura_cms',
    'Mvnforum': 'cpe:/a:mvnforum:mvnforum',
    'Mwforum': None,
    'Mybb': 'cpe:/a:mybb:mybb',
    'Nodebb': 'cpe:/a:nodebb:nodebb',
    'NoNonsense Forum': None,
    'October Cms': 'cpe:/a:octobercms:october',
    'Odoo': 'cpe:/a:odoo:odoo',
    'Opencart': 'cpe:/a:opencart:opencart',
    'Opencms': 'cpe:/a:alkacon:opencms',
    'Opentext Wsm': None,
    'Ophal': None,
    'Orchard': 'cpe:/a:orchardproject:orchard',
    'Pencilblue': None,
    'Percussion Cms': None,
    'Phorum': 'cpe:/a:phorum:phorum',
    'Php-nuke': 'cpe:/a:php-nuke:php-nuke',
    'Phpbb': 'cpe:/a:phpbb:phpbb',
    'Phpcms': 'cpe:/a:php:php',
    'Phpmyadmin': 'cpe:/a:phpmyadmin:phpmyadmin',
    'Phppgadmin': 'cpe:/a:phppgadmin:phppgadmin',
    'Phpwind': 'cpe:/a:phpwind:phpwind',
    'Pimcore': 'cpe:/a:pimcore:pimcore',
    'Plone': 'cpe:/a:plone:plone',
    'Presstopia': None,
    'Prestashop': 'cpe:/a:prestashop:prestashop',
    'Punbb': 'cpe:/a:punbb:punbb',
    'Quick.cms': 'cpe:/a:opensolution:quick.cms',
    'Rcms': 'cpe:/a:r_foundation:r',
    'Ritecms': 'cpe:/a:ritecms:ritecms',
    'Roadiz Cms': None,
    'Rock Rms': None,
    'Roundcube Webmail': 'cpe:/a:roundcube:roundcube_webmail',
    'Seamlesscms': None,
    'Serendipity': 'cpe:/a:serendipity:serendipity',
    'Sharepoint': None,
    'Silva': 'cpe:/a:infrae:silva',
    'Silverstripe': 'cpe:/a:silverstripe:silverstripe',
    'Simple Machines Forum': 'cpe:/a:simple_machines:simple_machines_forum',
    'Sitecore': None,
    'Sitefinity': 'cpe:/a:progress:sitefinity',
    'Snews': 'cpe:/a:snews:snews',
    'Solodev': None,
    'Spin Cms': None,
    'Squirrelmail': 'cpe:/a:squirrelmail:squirrelmail',
    'Subrion Cms': 'cpe:/a:subrion:subrion_cms',
    'Sulu': None,
    'Textpattern': 'cpe:/a:textpattern:textpattern',
    'Tiddlywiki': None,
    'Tikiwiki': None,
    'Typo3': 'cpe:/a:typo3:typo3',
    'UBB.threads': 'cpe:/a:ubbcentral:ubb.threads',
    'Uknowva': None,
    'Ultimate Php Board': 'cpe:/a:ultimate_php_board:ultimate_php_board',
    'Ushahidi Platform': 'cpe:/a:ushahidi:ushahidi_platform',
    'Umbraco': 'cpe:/a:umbraco:umbraco',
    'Umi Cms': 'cpe:/a:umi-cms:umi_cms',
    'Vanilla Forums': 'cpe:/a:vanillaforums:vanilla_forums',
    'Vbulletin': 'cpe:/a:vbulletin:vbulletin',
    'Webflow Cms': None,
    'Webgui': 'cpe:/a:webgui:webgui',
    'Websitebaker': 'cpe:/a:website_baker:website_baker',
    'Wolf Cms': 'cpe:/a:wolfcms:wolf_cms',
    'Wordpress': 'cpe:/a:wordpress:wordpress',
    'Xenforo': None,
    'Xmb': 'cpe:/a:xmb_forum:xmb',
    'Xoops': 'cpe:/a:xoops:xoops',
    'Yabb': 'cpe:/a:yabb:yabb',
    'Yazd Discussion Forum': 'cpe:/a:yazd:yazd_discussion_forum',
    'Yet Another Forum.net': 'cpe:/a:yet_another_forum.net:yet_another_forum.net',
    'Zen Cart': 'cpe:/a:zen-cart:zen_cart',
    'Zen Photos': None,
    '1C-Bitrix': None,
    'AMP Plugin': None,
    'Arc Publishing': None,
    'Adobe Experience Manager': None,
    'Amiro.CMS': 'cpe:/a:amirocms:amiro.cms',
    'Apostrophe CMS': None,
    'BIGACE': 'cpe:/a:bigace:bigace',
    'Backdrop': 'cpe:/a:backdropcms:backdrop',
    'Banshee': 'cpe:/a:banshee-project:banshee',
    'BoldGrid': None,
    'BOOM': None,
    'Brightspot': None,
    'Cargo': None,
    'Chameleon': None,
    'Chamilo': None,
    'Chorus': None,
    'Coaster CMS': 'cpe:/a:web-feet:coaster_cms',
    'Contensis': None,
    'CppCMS': 'cpe:/a:cppcms:cppcms',
    'DM Polopoly': None,
    'DTG': None,
    'DataLife Engine': 'cpe:/a:datalifecms:datalife_engine',
    'Dokeos': 'cpe:/a:dokeos:dokeos',
    'Dotclear': 'cpe:/a:dotclear:dotclear',
    'DovetailWRP': None,
    'Dynamicweb': None,
    'Eleanor CMS': 'cpe:/a:eleanor-cms:eleanor_cms',
    'Fork CMS': 'cpe:/a:fork-cms:fork_cms',
    'GX WebManager': None,
    'GoDaddy Website Builder': None,
    'Google Sites': None,
    'Graffiti CMS': None,
    'Green Valley CMS': None,
    'Hinza Advanced CMS': None,
    'Bloomreach': None,
    'Homeland': None,
    'IBM WebSphere Portal': None,
    'ImpressCMS': 'cpe:/a:impresscms:impresscms',
    'InProces': None,
    'Indico': None,
    'InstantCMS': 'cpe:/a:instantcms:instantcms',
    'Jahia DX': None,
    'Kentico CMS': 'cpe:/a:kentico:kentico',
    'Koha': 'cpe:/a:koha:koha',
    'Kolibri CMS': 'cpe:/a:senkas:kolibri',
    'Komodo CMS': 'cpe:/a:komodo:komodo_cms',
    'Koobi': 'cpe:/a:dream4:koobi',
    'Kotisivukone': None,
    'LightMon Engine': None,
    'Lithium': None,
    'Locomotive': None,
    'MYPAGE Platform': None,
    'Botble CMS': None,
    'MaxSite CMS': 'cpe:/a:maxsite:maxsite',
    'Melis CMS V2': None,
    'Methode': None,
    'Moguta.CMS': None,
    'Mono.net': None,
    'Mozard Suite': None,
    'Mynetcap': None,
    'Neos CMS': 'cpe:/a:typo3:neos',
    'Nepso': None,
    'OpenNemas': None,
    'PANSITE': None,
    'PHP-Fusion': 'cpe:/a:php-fusion:php-fusion',
    'Pagekit': 'cpe:/a:pagekit:pagekit',
    'Pagevamp': None,
    'Pars Elecom Portal': None,
    'Pingoteam': None,
    'PlatformOS': None,
    'Pligg': 'cpe:/a:pligg:pligg',
    'Posterous': None,
    'Proximis Omnichannel': None,
    'Public CMS': 'cpe:/a:publiccms:publiccms',
    'PyroCMS': 'cpe:/a:pyro_project:pyro',
    'RBS Change': None,
    'Rayo': None,
    'Redaxscript': 'cpe:/a:redaxscript:redaxscript',
    'S.Builder': None,
    'Scenari': None,
    'SDL Tridion': None,
    'SIMsite': None,
    'SPIP': 'cpe:/a:spip:spip',
    'Sarka-SPIP': None,
    'Scholica': None,
    'SeamlessCMS': None,
    'Simplébo': None,
    'SiteEdit': None,
    'Sivuviidakko': None,
    'SmartSite': None,
    'SpinCMS': None,
    'Squarespace': None,
    'Storyblok': None,
    'Strapi': 'cpe:/a:strapi:strapi',
    'Telescope': 'cpe:/a:telescopeapp:telescope',
    'TN Express Web': None,
    'Thelia': None,
    'Tilda': None,
    'Translucide': None,
    'Twilight CMS': 'cpe:/a:twilightcms:twilight_cms',
    'UMI.CMS': 'cpe:/a:umi-cms:umi.cms',
    'VIVVO': 'cpe:/a:vivvo:vivvo',
    'Vigbo': None,
    'Vignette': 'cpe:/a:vignette:vignette',
    'WebPublisher': None,
    'Webs': None,
    'WebsPlanet': None,
    'Website Creator': None,
    'Weebly': None,
    'Webzi': None,
    'Wix': None,
    'Woosa': None,
    'XpressEngine': None,
    'iEXExchanger': None,
    'Zendesk': None,
    'a-blog cms': 'cpe:/a:a-blog:a-blog',
    'eSyndiCat': 'cpe:/a:esyndicat:esyndicat',
    'enduro.js': None,
    'govCMS': None,
    'imperia CMS': None,
    'io4 CMS': None,
    'openEngine': 'cpe:/a:openengine:openengine',
    'papaya CMS': 'cpe:/a:papaya:papaya_cms',
    'PhotoShelter': None,
    'phpSQLiteCMS': 'cpe:/a:phpsqlitecms:phpsqlitecms',
    'phpwind': 'cpe:/a:phpwind:phpwind',
    'pirobase CMS': None,
    'Siteglide': None,
    'swift.engine': None,
    'uCore': None,
    'uCoz': None,
    'webEdition': 'cpe:/a:webedition:webedition',
    'wisyCMS': None,
    'Halo': 'cpe:/a:halo:halo',
    'Rocket': None,
    'Bootstrap': 'cpe:/a:getbootstrap:bootstrap',
    'Angular Material': None,
    'CakePHP': 'cpe:/a:cakephp:cakephp',
    'CodeIgniter': 'cpe:/a:codeigniter:codeigniter',
    'Django': 'cpe:/a:django_project:django',
    'Google/Web Toolkit': 'cpe:/a:google:web_toolkit',
    'Expressjs/Express': 'cpe:/a:expressjs:express',
    'Laravel': 'cpe:/a:laravel:laravel',
    'Ruby on Rails': 'cpe:/a:ruby_on_rails:ruby_on_rails',
    'Symfony': 'cpe:/a:sensiolabs:symfony',
    'Yiiframework': 'cpe:/a:yiiframework:yiiframework',
    'Akka HTTP': 'cpe:/a:lightbend:akka_http',
    'Amber': None,
    'AngularDart': None,
    'Apache/Wicket': 'cpe:/a:apache:wicket',
    'Banshee-project/Banshee': 'cpe:/a:banshee-project:banshee',
    'Blade': None,
    'Blazor': None,
    'Bonfire': None,
    'CherryPy': 'cpe:/a:cherrypy:cherrypy',
    'Sencha/Connect': 'cpe:/a:sencha:connect',
    'Dancer': 'cpe:/a:dancer:dancer',
    'Fat-Free Framework': None,
    'Flask': 'cpe:/a:palletsprojects:flask',
    'Includable': None,
    'Ionic': None,
    'Java Servlet': None,
    'JavaServer Faces': None,
    'JavaServer Pages': None,
    'Kemal': None,
    'Koa': None,
    'Koala Framework': None,
    'Kohanaframework/Kohana': 'cpe:/a:kohanaframework:kohana',
    'Laravel/Laravel': 'cpe:/a:laravel:laravel',
    'Liftweb/Lift': 'cpe:/a:liftweb:lift',
    'Lighty': None,
    'Mojolicious': 'cpe:/a:mojolicious:mojolicious',
    'Mono Project/Mono': 'cpe:/a:mono-project:mono',
    'Neos Flow': None,
    'Nette Framework': None,
    'Playframework/Play Framework': 'cpe:/a:playframework:play_framework',
    'Revel': None,
    'Sapper': None,
    'Phoenixframework/Phoenix': 'cpe:/a:phoenixframework:phoenix',
    'Shiny': None,
    'Snap': None,
    'Swiftlet': None,
    'ThinkPHP': 'cpe:/a:thinkphp:thinkphp',
    'TwistPHP': None,
    'Vaadin': 'cpe:/a:vaadin:vaadin',
    'Web2py': 'cpe:/a:web2py:web2py',
    'Xeora': None,
    'Zkoss/Zk Framework': 'cpe:/a:zkoss:zk_framework',
    'actionhero.js': None,
    'Angular': None,
    'AngularJS': 'cpe:/a:angularjs:angularjs',
    'Backbone.js': None,
    'Dojo': 'cpe:/a:dojotoolkit:dojo',
    'ef.js': None,
    'FancyBox': 'cpe:/a:fancybox_project:fancybox',
    'Handlebars': None,
    'Jquery': 'cpe:/a:jquery:jquery',
    'Lightbox': None,
    'Modernizr': None,
    'Moment.js': None,
    'MooTools': None,
    'Mustache.js': 'cpe:/a:mustache.js_project:mustache.js',
    'Prototype Javascript Framework': 'cpe:/a:prototypejs:prototype_javascript_framework',
    'React': 'cpe:/a:facebook:react',
    'RequireJS': None,
    'TweenMax': None,
    'Underscore.js': None,
    'A-Frame': None,
    'AMP': None,
    'Apollo': 'cpe:/a:ctrip:apollo',
    'AlloyUI': None,
    'Ant Design': None,
    'Aurelia': None,
    'BEM': None,
    'Boba.js': None,
    'Bootstrap Table': None,
    'Catberry.js': None,
    'Chart.js': None,
    'Clipboard.js': None,
    'D3': None,
    'DHTMLX': None,
    'DataTables': 'cpe:/a:sprymedia:datatables',
    'Day.js': None,
    'Element UI': None,
    'Ember.js': 'cpe:/a:emberjs:ember.js',
    'Enyo': None,
    'Epoch': None,
    'Essential JS 2': None,
    'Exhibit': None,
    'ExtJS': 'cpe:/a:jack_slocum:ext_js',
    'Fingerprintjs': None,
    'Flickity': None,
    'Gatsby': None,
    'GoJS': None,
    'Google Charts': None,
    'Hammer.js': None,
    'HeadJS': None,
    'Highcharts': 'cpe:/a:highcharts:highcharts',
    'Bokeh': None,
    'Highlight.js': None,
    'Highstock': None,
    'Hogan.js': None,
    'Immutable.js': None,
    'InfernoJS': None,
    'JS Charts': None,
    'JavaScript Infovis Toolkit': None,
    'Kibana': 'cpe:/a:elastic:kibana',
    'KineticJS': None,
    'Knockout.js': None,
    'Lazy.js': None,
    'List.js': None,
    'Lodash': 'cpe:/a:lodash:lodash',
    'Marionette.js': None,
    'Marked': 'cpe:/a:marked_project:marked',
    'MathJax': 'cpe:/a:mathjax:mathjax',
    'Mean.io': None,
    'MediaElement.js': 'cpe:/a:mediaelementjs:mediaelement.js',
    'Mermaid': None,
    'Meteor': None,
    'Mithril': None,
    'MobX': None,
    'MochiKit': None,
    'Moment Timezone': None,
    'Moon': None,
    'NVD3': None,
    'Next.js': 'cpe:/a:zeit:next.js',
    'OpenUI5': 'cpe:/a:sap:openui5',
    'PDF.js': None,
    'Paper.js': None,
    'Paths.js': None,
    'Phaser': 'cpe:/h:xerox:phaser',
    'Plotly': 'cpe:/a:plot:plotly',
    'Polyfill': None,
    'Polymer': None,
    'Protovis': None,
    'Ramda': None,
    'Raphael': None,
    'Reveal.js': None,
    'Rickshaw': None,
    'RightJS': None,
    'Riot': 'cpe:/o:riot-os:riot',
    'RxJS': None,
    'Sails.js': None,
    'Select2': 'cpe:/a:select2:select2',
    'Sencha Touch': None,
    'Slick': None,
    'Slimbox': None,
    'Slimbox 2': None,
    'Snap.svg': None,
    'Socket.io': 'cpe:/a:socket:socket.io',
    'SoundManager': None,
    'Strapdown.js': None,
    'Supersized': None,
    'Svelte': None,
    'SweetAlert': None,
    'SweetAlert2': None,
    'Timeplot': None,
    'Transifex': 'cpe:/a:transifex:transifex',
    'Twitter Flight': None,
    'Twitter typeahead.js': None,
    'Vue.js': None,
    'Nuxt.js': 'cpe:/a:nuxtjs:nuxt.js',
    'Webix': None,
    'Wink': 'cpe:/a:wink:wink',
    'XRegExp': None,
    'Xajax': 'cpe:/a:xajax:xajax',
    'YUI': 'cpe:/a:yahoo:yui',
    'Zepto': None,
    'Zone.js': None,
    'amCharts': None,
    'basket.js': None,
    'jQuery Migrate': None,
    'jQuery Sparklines': None,
    'jQuery UI': 'cpe:/a:jqueryui:jquery_ui',
    'jqPlot': None,
    'math.js': 'cpe:/a:mathjs:math.js',
    'particles.js': None,
    'prettyPhoto': 'cpe:/a:no-margin-for-error:prettyphoto',
    'script.aculo.us': 'cpe:/a:script.aculo.us:script.aculo.us',
    'scrollreveal': None,
    'shine.js': None,
    'styled-components': None,
    'three.js': None,
    'total.js': 'cpe:/a:totaljs:total.js',
    'xCharts': None,
    'AsciiDoc': None,
    'Microsoft/ASP.NET': 'cpe:/a:microsoft:asp.net',
    'CFML': None,
    'Dart': None,
    'Erlang': 'cpe:/a:erlang:erlang',
    'Haskell': None,
    'Go': 'cpe:/a:golang:go',
    'Java': 'cpe:/a:apple:java',
    'Lua': 'cpe:/a:lua:lua',
    'Node.js': 'cpe:/a:joyent:node.js',
    'Perl': 'cpe:/a:perl:perl',
    'PHP': 'cpe:/a:php:php',
    'Python': 'cpe:/a:python:python',
    'Rdf': None,
    'Ruby': 'cpe:/a:ruby-lang:ruby',
    'Scala': 'cpe:/a:scala-lang:scala',
    'Allegrosoft/RomPager': 'cpe:/a:allegrosoft:rompager',
    'Amazon/EC2': 'cpe:/a:amazon:ec2_api_tools_java_library',
    'AOLserver': 'cpe:/a:aol:aol_server',
    'Apache': 'cpe:/a:apache:apache',
    'Apache/Traffic Server': 'cpe:/a:apache:traffic_server',
    'Artifactory/Web Server': 'cpe:/a:codesys:web_server',
    'BaseHTTP': None,
    'Boa': 'cpe:/a:boa:boa',
    'Caddy': 'cpe:/a:caddy_project:caddy',
    'Cherokee': 'cpe:/a:cherokee:cherokee',
    'CompaqHTTPServer': 'cpe:/a:compaq:compaqhttpserver',
    'Apache/CouchDB': 'cpe:/a:apache:couchdb',
    'Cowboy': None,
    'ELOG HTTP': None,
    'EmbedThis/Appweb': 'cpe:/a:embedthis:appweb',
    'G-WAN': None,
    'EmbedThis/GoAhead': 'cpe:/a:embedthis:goahead',
    'Google/Web Server': 'cpe:/a:codesys:web_server',
    'Gunicorn/gunicorn': 'cpe:/a:gunicorn:gunicorn',
    'Hiawatha': 'cpe:/a:hiawatha-webserver:hiawatha',
    'HHVM': 'cpe:/a:facebook:hhvm',
    'HP/ChaiServer': None,
    'HP/Compact Server': None,
    'HP/iLO': None,
    'IBM/HTTP Server': 'cpe:/a:ibm:http_server',
    'IBM/Tivoli Storage Manager': 'cpe:/a:ibm:tivoli_storage_manager',
    'Indy': None,
    'Intel/Active Management Technology': 'cpe:/o:intel:active_management_technology',
    'Kestrel': None,
    'libwww-perl-daemon': None,
    'mini_httpd': 'cpe:/a:acme:mini-httpd',
    'National Instruments/LabVIEW': 'cpe:/a:national_instruments:labview',
    'Lighttpd': 'cpe:/a:lighttpd:lighttpd',
    'LiteSpeed Web Server': 'cpe:/a:litespeed_technologies:litespeed_web_server',
    'Logitech/Media Server': 'cpe:/a:logitech:media_server',
    'Microsoft/IIS': 'cpe:/a:microsoft:iis',
    'Microsoft/HTTPAPI': None,
    'MiniServ': None,
    'Mochiweb Project/MochiWeb': 'cpe:/a:mochiweb_project:mochiweb',
    'Mongrel/Mongrel': 'cpe:/a:mongrel:mongrel',
    'Mongoose': 'cpe:/a:cesanta:mongoose',
    'Monkey Http Daemon': 'cpe:/a:monkey-project:monkey_http_daemon',
    'Nginx': 'cpe:/a:nginx:nginx',
    'OpenBSD/httpd': None,
    'OpenGSE': None,
    'OpenResty': 'cpe:/a:openresty:openresty',
    'Oracle/Http Server': 'cpe:/a:oracle:http_server',
    'Rejetto/Http File Server': 'cpe:/a:rejetto:http_file_server',
    'RX Web Server': None,
    'nghttpx - HTTP/2 proxy': None,
    'SimpleHTTP': None,
    'Splunkd': None,
    'Starlet': None,
    'Tengine': None,
    'Tornadoweb/Tornado': 'cpe:/a:tornadoweb:tornado',
    'Thttpd': 'cpe:/a:acme:thttpd',
    'TwistedWeb': None,
    'Warp': None,
    'Yaws': 'cpe:/a:yaws:yaws',
    'Zeus Web Server': 'cpe:/a:zeus:zeus_web_server',
    'Zend/Server': 'cpe:/a:zend:server',
    'Microsoft/SQL Server': 'cpe:/a:microsoft:sql_server',
    'MySQL': 'cpe:/a:mysql:mysql',
    'Oracle/Database Server': 'cpe:/a:oracle:database_server',
    'Postgresql': 'cpe:/a:postgresql:postgresql',
    'Openssh': 'cpe:/a:openbsd:openssh',
    'Dropbear SSH': 'cpe:/a:dropbear_ssh_project:dropbear_ssh',
}
